name: Automatically Deployment

on: 
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    
    steps:
      - name: Create .env file
        run: |
          jq -r 'to_entries|map("\(.key)=\(.value|tostring)")|.[]' <<< "$SECRETS_CONTEXT" > .env
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
